<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- enable field keyword -->
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>jjb</Authors>
		<Company>$(Authors)</Company>
		<Product>Background Remover</Product>
		<Description>Background Remover</Description>
		<Version>1.2.0.0</Version>
		<NeutralLanguage>en</NeutralLanguage>
		<Copyright>Copyright © $([System.DateTime]::Now.Year) $(Authors)</Copyright>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
	</PropertyGroup>
	
	<!-- paint.net dependencies -->
	<!-- This is necessary so that the build copies the version of nuget packages we're referencing,
         instead of copying the ones that Paint.NET is using (which may be trimmed and/or a different version) -->
	<PropertyGroup>
		<ImportWindowsDesktopTargets>True</ImportWindowsDesktopTargets>
		<UseWindowsForms>True</UseWindowsForms>
		<CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<ProduceReferenceAssembly>False</ProduceReferenceAssembly>
		<Deterministic>False</Deterministic>
	</PropertyGroup>

	<PropertyGroup>
		<!-- MSB3277 removes the harmless and unhelpful warning about assembly version "conflicts" (e.g. System.Runtime.Serialization.Formatters) -->
		<NoWarn>1701;1702;CS7035;MSB3277</NoWarn>
	</PropertyGroup>
	
	<PropertyGroup>
		<PdnRoot>C:\Program Files\paint.net</PdnRoot>
	</PropertyGroup>

	<!-- copy to paint.net effects directory -->
	<PropertyGroup>
		<PostBuildEvent>
			xcopy /Y /Q /S /I "$(OutDir)*" "$(PdnRoot)\Effects\BackgroundRemover"
		</PostBuildEvent>
	</PropertyGroup>
		
	<ItemGroup>
		<Reference Include="PaintDotNet.Base">
			<HintPath>$(PdnRoot)\PaintDotNet.Base.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.ComponentModel">
			<HintPath>$(PdnRoot)\PaintDotNet.ComponentModel.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.Core">
			<HintPath>$(PdnRoot)\PaintDotNet.Core.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.Effects.Core">
			<HintPath>$(PdnRoot)\PaintDotNet.Effects.Core.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.Effects.Gpu">
			<HintPath>$(PdnRoot)\PaintDotNet.Effects.Gpu.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.Fundamentals">
			<HintPath>$(PdnRoot)\PaintDotNet.Fundamentals.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.Framework">
			<HintPath>$(PdnRoot)\PaintDotNet.Framework.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.Primitives">
			<HintPath>$(PdnRoot)\PaintDotNet.Primitives.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.PropertySystem">
			<HintPath>$(PdnRoot)\PaintDotNet.PropertySystem.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.Windows">
			<HintPath>$(PdnRoot)\PaintDotNet.Windows.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.Windows.Core">
			<HintPath>$(PdnRoot)\PaintDotNet.Windows.Core.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.Windows.Framework">
			<HintPath>$(PdnRoot)\PaintDotNet.Windows.Framework.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="PaintDotNet.ObjectModel">
			<HintPath>$(PdnRoot)\PaintDotNet.ObjectModel.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<!-- assets/localization -->
	<ItemGroup>
		<None Remove="Assets\ic_fluent_video_background_effect_24_filled.ico" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\ic_fluent_video_background_effect_24_filled.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Assets\Localization\strings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Strings.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Assets\Localization\Strings.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>strings.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>